### ISSUE TITLE
Adjustable Front and Rear Delay

### ISSUE THREAD

**Issue by Kynuska** [jason0611/FS22_HeadlandManagement#42]
Hello.
I tested now with a lawn mower (butterfly). There could be a delay in lifting / lowering the front and rear devices. (Length of tractor or manually?) Delay in seconds if necessary.
Thanks.
Ales

**Comment by jason0611** [comment]
Hello Kynuska,
that's on the list. :-) 
I'm still not sure how to realize it best, but I will look into it in one of the next versions.
Regards,
Martin

**Comment by Kynuska** [comment]
I don't know any programming language, just the basics of elementary school 30 years ago.
So just a logical idea of how to do it mathematically.
The game knows the length of the tractor and the set speed at the headland. From this, it should be possible to calculate the delays of the front and rear tools by a simple formula (t = s: v).
Good when entering the headland, worse when leaving it, when the tractor accelerates to working speed. (I don't know if he knows here).
But I guess that's probably not the problem. That problem will be in how to get it into the script.
K.

**Comment by jason0611** [comment]
I have expressed myself somewhat misleadingly:
I wasn't sure, what will be the *best* way to implement, because I have some ideas how to make it, but I have to test out, what will work best. The main goal is, that it has to work with almost all addressed vehicles in the game, including mods.
The approach I will try first, is to remember the position of the vehicle's rootNode and then to wait until the distance of the vehicle to this point reaches the vehicle's length value. So it will be independent of the vehicle's speed.
Because this has to be tested intensively, I will put this feature into one of the next versions after ModHub-Release.
